### ISSUE TITLE
Tier 8 and 9 Rockets don't appear in lander/parachest upon landing

### ISSUE THREAD

**Issue by TheMCSpacePro** [Arrokoth486958/The_Sol-A_Galacticraft_addon#3]
The bug here is basically what's stated in the title. When launching from a Tier 8 **and/or** Tier 9 rocket, the lander (or when turning off the moon lander via GC's config, the parachest) neither the launch pad nor the rocket are in there, making it so that a spare rocket (or /gchouston) are required to make it home.

**Comment by Arrokoth486958** [comment]
Well...Sorry I don't have time to make updates...
~~If you know something about nodding, you can try it by ur self.~~

**Comment by TheMCSpacePro** [comment]
Alright, well if you're able to find the time for a final update, this might be one game-breaking bug you'll want to fix.

**Comment by Arrokoth486958** [comment]
Okay, here is some good news for you: I've fixed this Bug. You can find it in Release on the github page

**Comment by TheMCSpacePro** [comment]
Not closing yet as this bug still occurs in the GitHub released jar.

**Comment by Arrokoth486958** [comment]
~~Oh yeah ur right~~
